############################################################
# +------------------------------------------------------+ #
# |   Сообщения                                          | #
# +------------------------------------------------------+ #
############################################################

messages:

  errors:
    only-for-players: "Данная команда доступна только игрокам на сервере!"
    don't-have-permissions-to-do: "΃ У Вас недостаточно прав для выполнения данного действия!"
    don't-have-permissions-command: "΃ У Вас недостаточно прав для использования данной команды!"

  help:
    requests:
      header: "<#ffffff>Команды взаимодействия с приглашениями:"
      accept: "<#FDAEE0><bold>/request accept <#AAAAAA>— <#ffffff>Принять приглашение."
      decline: "<#FDAEE0><bold>/request decline <#AAAAAA>— <#ffffff>Отклонить приглашение."