main:
  debug: true

############################################################
# +------------------------------------------------------+ #
# |                 Effects and sounds                   | #
# +------------------------------------------------------+ #
############################################################

effects-sounds:
  # Sound when an error occurs.
  error-sound:
    name: "block.note_block.didgeridoo"
    pitch: 1
    volume: 1